import Head from 'next/head';
import Avatar from '../components/avatar';
import { ViewGridIcon, MicrophoneIcon } from '@heroicons/react/solid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />

          <Avatar url='http://via.placeholder.com/200' />
        </div>
      </header>
    </div>
  );
}
